### ISSUE TITLE
Website Updates 2022-2023 (lots of info)

### ISSUE THREAD

**Issue by toluam** [temporalecologylab/labgit#5] opened 2022-06-22 23:38 UTC
A place to note tasks and progress

**Comment by toluam** [comment] 2022-08-20 17:55
I'm having some issues with integrating the website content with the old theme into the new theme. I've sent an email to Phoebe to see if she had any of the same issues while updating the State of Wine website so I'll see if she has any advice and go from there

**Comment by lizzieinvancouver** [comment] 2022-08-21 01:47
@toluam I think she did, and I think her advice was just to rebuild the site, especially as we want to switch to Elementor. If you don't hear back from her, then that is my advice! You may want to see if you can build it separately (so you have time) then switch the temporalecology.org URL when it's ready.

**Comment by toluam** [comment] 2022-09-02 18:29
@lizzieinvancouver the website is almost ready to go! I just need to populate it with images, most of which I can pull from the lab images drive. Although, I can't seem to find photos for lab members to fill the "people" and "previous people" pages. Do you have any ideas for where I could find these?

**Comment by lizzieinvancouver** [comment] 2022-09-12 10:29
@toluam Wow, that was so fast!

This is a great question. I personally have a folder on my computer (note to self: Website/temporalecology/images/people) with the little circle photos of many people up until 2018 (maybe). I suspect we keep the rest elsewhere, hopefully on the Drive. Can you ask @sophiacc01
about this and report back? If she does not know, ask Phoebe. 

Hopefully we are doing something organized. If not, no time to start but the present! So ask them for whatever they have and we can figure out a common place to put things. 

Thanks for your work on this.

**Comment by lizzieinvancouver** [comment] 2023-01-16 09:51
HOMEPAGE: https://temporalecology.org/

Edits to welcome text:

Welcome to the Temporal Ecology Lab. We’re focused on understanding how global changes alter the temporal assembly and disassembly of communities. Much of the research in the lab centers on understanding recent shifts in `biological spring,’ advances in the timing of plants’ leafout and flowering that have occurred in many regions of the globe with climate change.

We're primarily field computational ecologists, working to build generative models of ecological systems. As such most of us split our time between collecting and analyzing field data, working on meta-analyses of contemporary and historical data or setting up experiments in and out of doors to test our mechanistic models. Given the combination of our aims and data, we often use Bayesian approaches. 

Current projects in the lab use meta-analyses, growth-chamber studies, continental field transects, winegrape harvest data and more to understand the temporal dimension of populations, communities and ecosystems. We’re based in the department of Forest and Conservation Sciences at the University of British Columbia, with field sites across North America and collaborators who make our research more innovative, creative and useful from across the world. 

Small tweaks:

1. There isn't any way to delete 'temporal ecology lab' from the header on the homepage? I really don't like how it says it twice there (but I don't want to delete our lab name from the middle of the page!).
2. Updates from our Blog! --> Updates from our tumblr
3. Can you change the cyan color on the lab name and search square to something less bright? It's also the color at the top of the drop down menus, so this must be a global attribute we can change.... Actually if you can tell me where to find this attribute I will play around with the colors.

**Comment by lizzieinvancouver** [comment] 2023-01-16 12:32
For the PEOPLE page ....

1. Yikes! All the links seem gone. Please find them and reinstate them. You can skip email addresses of people no longer in the lab, but we need to keep including the website (of everyone who has one) of anyone who has one, whether they are on the 'people' or 'previous people page' and I will email you my CV.
2. Also, something bad has happened as people have disappeared.... **can you post the other version of the website somewhere so we can compare?** Ailene Ettinger, Geoff Legault, Ignacio Morales-Castilla are all gone from all pages. This is not good .... 
3. Please move Faith, and Kristian to 'previous people' If you need to, reach out to Faith, Dan etc. to make sure we have their updated websites. 
4. Please update the StateofWine website also so that the people on 'people' versus 'previous people' are the same across the two sites.

**Comment by lizzieinvancouver** [comment] 2023-01-16 12:38
@toluam A lot of the links between pages are broken -- for example, the link to the 'previous people' from 'people' and almost all the links from the Tree Spotters page. This should have been fixed before the site went live so please fix soon.

**Comment by toluam** [comment] 2023-01-17 01:59
@lizzieinvancouver Looks like a lot of the links broke during the domain transfer process, also a lot of the shortcuts to other pages are still attached to the temporary domain so now that it no longer exists, those pages don't open (mostly an issue with the treespotters). I've updated the temporal ecology people page so it has the right information and working links and will do the same with state of wine and treespotters. The old website is still available on site ground as alt.temporalecology.org.

**Comment by lizzieinvancouver** [comment] 2023-01-17 10:05
@toluam Amazing! Looking at the old site reminds me how much I love our new site you built (and is helpful for me to find things).

- [ ] I just noticed that all the PDF links in the publications page also broke so can you fix those as well (PDF and supp links)?

**Comment by lizzieinvancouver** [comment] 2023-01-17 10:38
RESEARCH PAGE! https://temporalecology.org/research/

A) 

Okay, so a lot of this text is ... um ... 10 years old! Thus, I suggest we move some of it to a new webpage that we link to. That new page should NOT be in the menu -- you can only find it from this page. So at the bottom of this page, add:

Our previous work, including detritus in food webs and comparing field experiments with long-term phenology data, is explained here. (And link 'here' to a new page, make sure you always pick 'opens in a new window')'

Then move these sections to that page:
Detritus in food webs 
	- all subsections
Phenology of wild plant species
	- Forecasting phenology: Integrating ecology, climatology, and phylogeny to understand plant responses to climate change
	- Predicting future springs: Reconciling experimental and observational approaches for climate change impacts

B) 

Okay, then update this page as follows:

New sections (with links to them at the top the way we currently have 'Phenology of Wild Species | Detritus | Open science')

So the new link at top would be: 'Temperature response curves | Temporal assembly | Trophic mismatch | Open science|

Right below the links KEEP the text we have but add to the end of the winegrape sentence ... 

"In addition to the below work, the lab also works on winegrapes [keep link], which we now cover in a whole website that includes some of our favorite resources on understanding climate change: State of Wine. (And be sure to change the link here to https://stateofwine.org/).


SECTION What is the temperature response to climate change by plants and animals?

Biological time has been reshaped by anthropogenic warming. This is highlight by shifts in phenology, the study of the different stages of plant growth and the transitions between them. The phenology of many plants and animals is primarily driven by temperature and decades of lab studies highlight a common temperature response curve, where response rates increase with warmer temperatures until some optimum then crash or stall. Yet global change biology has struggled to adapt this common response to outside the lab. Our lab is working to overcome this disconnect with more realistic models of temperature response, and by interrogating how responses compare across methods and scales to identify drivers of variation. 

We recently highlighted major variation due to the complexity of measuring ‘time’ as climate change accelerates biological responses. We showed that dozens of studies finding that sensitivity to temperature has declined with warming can be predicted from the non-linearity of temperature responses. Read more in Global Change Biology [put journal titles in italics and link to: https://temporalecology.org/wp-content/uploads/2022/01/Wolkovich_etal_2021decsens.pdf]

Temperature is not the only fundamental driver of phenology, as daylength may also play a critical role, and could limit species responses to warming. Across species, we've used a massive meta-analysis of temperature x daylength experiments to show that winter temperatures are actually the strongest controllers of spring phenology in tress. We're now examining how strongly evolutionary history shapes responses to these cues. Across latitudes, results from our own common garden and a cross-continental meta-analysis of similar studies both confirm that tree phenological responses are strongly plastic in the spring and determined by local adaptation in the fall. Building on this, work led by Ailene Ettinger and Daniel Buonaiuto both highlighted how phenological events cannot be considered alone, as reproductive events---both their length and dispersal mode--shape the timing of growth. 

Read more about this work in (just list the journal names (in italics) and link to each of the PDFs that go with them):

Ettinger*, A.K., Chamberlain*, C.J., Buonaiuto*, D. M., Morales-Castilla*, I., Flynn*, D.F.B., Savas*, T., Samaha*, J. & E. M. Wolkovich. 2020. Winter temperatures predominate in spring phenological responses to warming. Nature Climate Change: 10 (12), 1137-1142.

Buonaiuto*, D. M., Morales-Castilla*, I., E. M. Wolkovich. 2020. Reconciling competing hypotheses regarding flower–leaf sequences in temperate forests for fundamental and global change biology. New Phytolo- gist.

Wolkovich, E. M., Chamberlain*, C.J., Buonaiuto*, D. M., Ettinger*, A.K. & I. Morales-Castilla.* 2022 How interactive effects of temperature and photoperiod shape plant phenology responses to warming. New Phytologist: 235: 1719-1728.

Buonaiuto*, D. M. & E. M. Wolkovich. 2021. Differences between flower and leaf phenological re- sponses to environmental variation drive shifts in spring phenological sequences of temperate woody plants. Journal of Ecology: (109): 2922–2933.

Ettinger*, A.K., Buonaiuto*, D. M., Chamberlain*, C.J., Morales-Castilla* & E. M. Wolkovich. 2021. Spatial and temporal shifts in photoperiod with climate change. New Phytologist: 230 (2), 462-474.


Better understanding phenology may also help us predict the winners and losers as climate change, as our lab has found that how well species track environmental change phenological connects to fitness. These studies, however, often consider phenology as a singular plant trait-—one that may critically influence plant performance and spread but is not tied to other major traits. In contrast, plant phenology could be considered as one of many correlated traits making up a plant’s trait syndrome. The lab is testing whether considering phenology as a critical plant trait correlated with other major functional traits can help understand assembly. 

You can read more about this work in (just list the journal names (in italics) and link to each of the PDFs that go with them -- listed below). Deirdre Loughnan has led a major study of how phenology correlates with other functional traits across North American forests. Hear more about her work here [include link].

Wolkovich, E. M. & A. K. Ettinger. 2014. Back to the future for plant phenology research. New Phytolo- gist 203: 1021–1023. (Commentary)

Flynn*, D. F. B. & E.M. Wolkovich. 2018. Temperature and photoperiod drive spring phenology across all species in a temperate forest community. New Phytologist. doi.org/10.1111/nph.15232


SECTION How does intra- and inter-annual time assemble communities?

In many ways our above work provides critical building blocks to our lab's greater aim---forecasting how phenology affects interspecific interactions. Our research program is extending community assembly theory, which has focused mainly on space and inter-annual timescales, to the intra-annual---phenological---timescale. 

The lab's work in this area began when Lizzie was a postdoc and worked on a framework for how intra-annual time and phenology could underlie invader success---a fundamental question in community assembly. Working with Megan Donahue [https://www.donahuelab.com/], she has extended it to a more general theory to show that tracking must trade-off with other traits for stable communities, and that environmental change can reshape the balance of equalizing versus stabilizing mechanisms. For this work, we adapted the storage effect model to include environmental tracking and non-stationary environments (environments that shift over time), and we plan to continue developing it to guide research. 


You can read more about this work in: (just list the journal names (in italics) and link to each of the PDFs that go with them -- listed below).

Wolkovich, E. M. & Donahue, M. 2021. How phenological tracking shapes species and communities in non-stationary environments. Biological Reviews: 10.1111/brv.12781.

Eyster, H.* & Wolkovich, E. M. 2021. Comparisons in the native and introduced ranges reveal little evidence of climatic adaptation in germination traits. Climate Change Ecology: doi.org/10.1016/j.eco- chg.2021.100023

24. Wolkovich, E. M. & E. E. Cleland. 2014. Phenological niches and the future of invaded ecosystems with climate change. AoB Plants doi:10.1093/aobpla/plu013.

22. Wolkovich, E. M., Davies, T. J., Schaefer, H., Cleland, E. E., Cook, B. I., Travers, S. E. , Willis, C. G. & C. C. Davis. 2013. Phenology and plant invasions: Climate change contributes to exotic species’ success in temperature-limited systems. American Journal of Botany 100(7): 1407-1421.

14. Wainwright, C. E., E. M. Wolkovich & E. E. Cleland. 2012. Seasonal priority effects: implications for invasion and restoration in a semi-arid system. Journal of Applied Ecology 49(1): 234-241. (Recommended by Faculty of 1000)

10. Wolkovich, E. M. & E. E. Cleland. 2011. The phenology of plant invasions: A community ecology per- spective. Frontiers in Ecology & the Environment 9(5): 287-294. (Recommended by Faculty of 1000)

These new models highlight how our research program is leading global efforts to integrate two critical parts of climate change---non-stationary environments and discrete events---into community assembly. During her PhD Cat Chamberlain showed frost events have increased across Europe with climate change, and highlighted how this can reshape plant growth. These discrete events result from climate change shifting both phenology and climatic events at once. The damage of events is dependent on the phenological stage---for example, frost damage peaks at budburst, and heat wave damage is highest at flowering---resulting in a complex interplay of climate drivers and effects, which we call `climate hazards.' Working with Frederik Baumgarten, the lab is developing a new program of experiments and models to understand and predict how these hazards impact plant growth.

You can read more about this work in: (just list the journal names (in italics) and link to each of the PDFs that go with them -- listed below).

Chamberlain*, C.J., Cook, B.I., Morales-Castilla*, I. & E. M. Wolkovich. 2020. Climate change reshapes the drivers of false spring risk across European trees. New Phytologist: 229 (1), 323-334

Chamberlain*, C.J & E. M. Wolkovich. 2021. Late spring freezes coupled with warming winters alter temperate tree phenology and growth. New Phytologist: (231) 987–995.

Wolkovich, E. M., Cook, B. I., McLauchlan, K. K. & T. J. Davies. 2014. Temporal ecology in the An- thropocene. Ecology Letters 17(11): 1365–1379.

SECTION How is climate changing reshaping trophic interactions?

Events are also shaped across trophic levels. My lab has been instrumental in advancing the study of trophic mismatch, both through advancing the underlying conceptual theory and through more robust meta-analyses, with new work in my lab showing clade-level---not trophic level---differences may underlie current reports of global trophic mismatch.  

You can read more about this work in: (just list the journal names (in italics) and link to each of the PDFs that go with them -- listed below).

Kharouba, H. M., Ehrlen, J., Gelman, A., Bolmgren, K., Allen, J. M., Travers, S. & E. M. Wolkovich. 2018. Global shifts in the phenological synchrony of species interactions over recent decades. PNAS: Apr 2018, ; DOI: 10.1073/pnas.1714511115

Kharouba, H. M. & E. M. Wolkovich. 2020. Disconnects between ecological theory and data in pheno- logical mismatch research. Nature Climate Change: https://doi.org/10.1038/s41558-020-0752-x


SECTION Open science needed to advance global change research

[This is almost the same text as what is there now -- look for EDITS, for where I made changes.]

Progress in global change research over the last 30 years has come alongside a distinct shift towards synthetic work. Previously, excellent ecological research was underpinned by observations, experiments, and models often conducted by the same researcher or research group. Today, however, the best work includes syntheses of these three pillars of research through time and space, combining data, methods, and insights from disparate experiments, multiple long-term datasets, and theories.

Data sharing, often mandated in other fields, is generally low in ecology, and code for models and analyses is rarely included with publications. Such a lack of transparency forces ecologists to work without key data and analytical resources, retards collaboration, and impairs research with strong conservation relevance by making most findings difficult to study in depth, build upon, or reproduce. Although ‘open ecology’ appears to have potentially large benefits for the discipline, the vast majority of ecologists have never shared their data for a variety of perceived and real issues.

[EDITS] Working with Mary O’Connor, Jim Regetz and Lizzie put together an article that outlines and addresses the major concerns and advantages of data and code-sharing, and address the skill sets and logistical needs at the individual and lab-based level. You can download it here. Additionally Lizzie has talked about this issue in pieces at Nature here and here and Science Careers, served on the Scientific Advising Board of Dryad [link: https://datadryad.org/] and is now on the steering committee for the Environmental Data Science RCN, which is hosting summits to build this community (check out the 2023 meeting [https://eds-summit.github.io/]).

[EDITS] Our lab works to make all our data public. Check out our data and code management plan here [https://github.com/temporalecologylab/labgit/tree/master/datacodemgmt].

**Comment by lizzieinvancouver** [comment] 2023-01-17 10:39
Vin page: https://temporalecology.org/vin/

Just add a sentence at the top after 'The phenology & future of winegrapes': 

A few of our winegrape projects are listed below, but to learn much more, check out our separate website, State of Wine. (And be sure to change the link here to https://stateofwine.org/)

**Comment by lizzieinvancouver** [comment] 2023-01-17 10:45
Trying to keep track of tasks:

- [ ] @lizzieinvancouver check the people pages
- [ ] @lizzieinvancouver check other pages once updated (research/vin)
- [ ] @toluam Update text on research page (let's make this a priority item if you can, please!)
- [ ] @toluam Update the tiny bit of text on vin page
- [ ] @toluam Check all the internal links on pubs page
- [ ] @lizzieinvancouver check publications page
- [ ] @lizzieinvancouver check resources and other pages
- [ ] @toluam Tell @lizzieinvancouver as you update pages so she can review.

Whoo-hoo, the new website is great! Thank you!

**Comment by toluam** [comment] 2023-01-28 01:50
people, research, vin, and treespotters pages have been updated. 

@lizzieinvancouver I was unable to find this paper - Wolkovich, E. M., Davies, T. J., Schaefer, H., Cleland, E. E., Cook, B. I., Travers, S. E. , Willis, C. G. & C. C. Davis. 2013. Phenology and plant invasions: Climate change contributes to exotic species’ success in temperature-limited systems. American Journal of Botany 100(7): 1407-1421
Is there any chance this is the paper you're referring to? - Temperature-dependent shifts in phenology contribute to the success of exotic species with climate change (https://www.jstor.org/stable/23434493)

Still to do:
1. fix broken links in the publications page
2. delete 'temporal ecology lab' from the header on the homepage
3. find where to change the attribute colours
4. add my work to the master document for future reference

**Comment by lizzieinvancouver** [comment] 2023-01-31 09:17
@toluam Great! I will email you the missing paper. It looks to me like 'delete 'temporal ecology lab' from the header on the homepage' is done, no?

Thanks for getting the new research page up. However the page https://temporalecology.org/research/ is past research now. Can we change so current research has the URL https://temporalecology.org/research/ *and* so that past research is part of the drop down menu and not where you end up when you click on the main header of 'research' (currently when you click on the main header of research you end up on the past research page.

**Comment by lizzieinvancouver** [comment] 2023-01-31 09:18
@toluam And yes! I had the title on that paper wrong. Sorry about that.

**Comment by lizzieinvancouver** [comment] 2023-01-31 09:30
Update pubs page ...

Would you be able to check and update the broken links on the pubs page (https://temporalecology.org/publications/)?

You can see the old links via: alt.temporalecology.org and I can answer any questions. We should also add two papers from last year (2022):

Wolkovich, E. M., Chamberlain*, C.J., Buonaiuto*, D. M., Ettinger*, A.K. & I. Morales-Castilla.* 2022 How interactive effects of temperature and photoperiod shape plant phenology responses to warming. New Phytologist: 235: 1719-1728.

Ettinger*, A.K, Chamberlain*, C.J., & E. M. Wolkovich. 2022. The increasing relevance of phenology to conservation. Nature Climate Change (12): 305-309. (Invited, not peer-reveiwed)

Attached are the two papers. And you can add a 2023 line with this:

Kharouba, H. M. & E. M. Wolkovich. Lack of evidence for the match-mismatch hypothesis across te restrial trophic interactions. Accepted. Ecology Letters.

No PDF for that yet.

@soleil-nocturne123 let me know if you have time to help on this over email! Thanks.

**Comment by soleil-nocturne123** [comment] 2023-02-06 21:01
@lizzieinvancouver I have updated almost all the links for the [website publications page](https://temporalecology.org/publications/). I have some inquiries about this:

1. There are some links not working even for the previous websites (listed below):

- **Earlier:** Link not working
- **2011:** **Data** and **Faculty of 1000** for Wolkovich, E.M. & E.E. Cleland, **Data & Code** for Wilson, E.E. & E. M. Wolkovich
- **2012:** **Faculty of 1000** for Wolkovich, E.M. & 18 co-authors
- **2013:** **Article** and **HGB** for Pau, S., Wolkovich, E. M., Cook, B. I., Nytch, C., Regetz, J., Zimmerman, J. K. & S. J. Wright

2. There are some citations with no pdf attached. Do we have open access to those articles by now?

- **2011:** Nicholas, K. A., Wolkovich, E. M. & L. A. Webb
- **2012:** Pau, S, Gillespie, T.W., & E.M. Wolkovich
- **2015:** Seabloom, E. W. & 66 co-authors

And please let me know if I need to make additional changes.

**Comment by toluam** [comment] 2023-02-26 19:19
@lizzieinvancouver all pages should be updated. To play around with the site colours you can go to Appearance --> Customize --> Colours --> and select custom under colour scheme. I've currently changed it to a dark green.

**Comment by lizzieinvancouver** [comment] 2023-03-21 11:38
Closing this as it seems like all the stuff is done! Thank you @toluam.

**Comment by lizzieinvancouver** [comment] 2023-03-21 20:07
@soleil-nocturne123 Sorry I closed this. Thank you for catching that ...

Earlier: Link not working
2011: Data and Faculty of 1000 for Wolkovich, E.M. & E.E. Cleland, 

Data & Code for Wilson, E.E. & E. M. Wolkovich -- see https://datadryad.org/stash/dataset/doi:10.5061%2Fdryad.8612

2012: Faculty of 1000 for Wolkovich, E.M. & 18 co-authors

For the Faculty of 1000 stuff -- can you search the article name and/or authors and see if you find them new links here: https://f1000research.com/browse/faculty-reviews

2013: Article and HGB for Pau, S., Wolkovich, E. M., Cook, B. I., Nytch, C., Regetz, J., Zimmerman, J. K. & S. J. Wright
Make 'HGB' -> 'HGB's Jump in the line' and link to: https://www.youtube.com/watch?v=qFRbm1zuXA4 ... that was the theme song. And here's the article link: https://www.nature.com/articles/nclimate1934. ... should we add the PDF?

There are some citations with no pdf attached. Do we have open access to those articles by now?
2011: Nicholas, K. A., Wolkovich, E. M. & L. A. Webb -- I just emailed KA Nicholas!

2012: Pau, S, Gillespie, T.W., & E.M. Wolkovich -- emailed to you
2015: Seabloom, E. W. & 66 co-authors is open access here: https://www.nature.com/articles/ncomms8710 and I sent the PDF.

@soleil-nocturne123 Please review and let me know what I missed. Thank you!

**Comment by soleil-nocturne123** [comment] 2023-05-03 19:01
@lizzieinvancouver Hi Lizzie, I have fixed most of the links, except for:

- Data for **Wolkovich, E.M. & E.E. Cleland. 2011. The phenology of plant invasions: A community ecology perspective. Frontiers in Ecology & the Environment 9(5): 287-294.**
- 2 Faculty of 1000 links:
           -  Faculty of 1000 is only from 2012 onwards so I think the link for **2011: Wolkovich, E.M. & E.E. Cleland** might not exist anymore
           -  I couldn't find the link for **2012: Wolkovich, E.M. & 18 co-authors**

**Comment by lizzieinvancouver** [comment] 2023-05-18 10:19
@soleil-nocturne123 Thanks for your work on this!

Okay...

- Let's remove links for the missing F1000
- I will email you a PDF for 2012: Wolkovich, E.M. & 18 co-authors, and let's also add there after the PDF link: 'data from [NECTAR](https://knb.ecoinformatics.org/view/nceas.988.17) and [STONE](https://knb.ecoinformatics.org/view/doi%3A10.5063%2FF10V89RP)' with the links shown here
- What a weird link for the data for Wolkovich, E.M. & E.E. Cleland. 2011. The phenology of plant invasions: A community ecology perspective. Frontiers in Ecology & the Environment 9(5): 287-294! Let's change 'data' to 'data from Project [budburst](https://budburst.org/)' and link as shown here.

**Closed** 2023-05-20 16:03 UTC
